services:

  traefik:
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.network=proxy
      - --providers.docker.exposedbydefault=false

      - --providers.file.filename=/certs/tls.yml
      - --providers.file.watch=true

      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https

      - --log.level=INFO
      - --accesslog=true
      - --accesslog.format=json
      - --metrics.prometheus=true
      - --metrics.prometheus.addentrypointslabels=true
      - --metrics.prometheus.addserviceslabels=true
      - --tracing.otlp=true
      - --tracing.otlp.grpc.endpoint=tempo:4317
      - --tracing.otlp.grpc.insecure=true
      - --tracing.serviceName=traefik

    volumes:
      - ./certs:/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:8081:8080"
    networks:
      - proxy
      - sniply-observability
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`localhost`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.service=api@internal

  db:
    ports:
      - "5432:5432"
  redis:
    ports:
      - "6379:6379"

  api:
    ports:
      - "8080:8080"
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-dev.rule=Host(`api.localhost`)
      - traefik.http.routers.api-dev.entrypoints=websecure
      - traefik.http.routers.api-dev.tls=true

      - traefik.http.routers.api-dev.service=api-dev
      - traefik.http.services.api-dev.loadbalancer.server.port=8080
      - traefik.http.services.api-dev.loadbalancer.server.scheme=http

  api-debug:
    build:
      context: .
      dockerfile: Dockerfile
      target: debug
    profiles: ["debug"]
    environment:
      APP_PORT: "8080"
      DATABASE_URL: "postgres://sniply:${POSTGRES_PASSWORD}@db:5432/sniply?sslmode=disable"
      REDIS_URL: "redis://redis:6379/0"
      OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector:4317"
    ports:
      - "8080:8080"
      - "40000:40000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app
      - sniply-observability
      - proxy

  grafana:
    ports:
      - "3001:3000"  
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.localhost`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls=true
      - traefik.http.services.grafana.loadbalancer.server.port=3000
  prometheus:
    ports:
      - "9090:9090"
  loki:
    ports:
      - "3100:3100"
  tempo:
    ports:
      - "3200:3200"
  otel-collector:
    ports:
      - "4317:4317"
